### ISSUE TITLE
Node circular dependency warning on 4.x branch

### ISSUE THREAD

**Issue by chrisschultze** [launchdarkly/js-sdk-common#84]
**Describe the bug**
Using node-client-sdk, running a file that imports LaunchDarkly displays circular dependency warnings related to 'messages' in the terminal.

**To reproduce**
1. install launchdarkly-node-client-sdk@2.2.1 in a project
3. run node on the following code snippet in a terminal (might need to add "type": "module" in package.json):
`
import * as LaunchDarkly from 'launchdarkly-node-client-sdk';
`

**Expected behavior**
No warnings to display in the terminal

**Logs**

(node) Warning: Accessing non-existent property 'messages' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:748:11)
    at Object.get (node:internal/modules/cjs/loader:764:5)
    **at Object.<anonymous> (/home/$USER/source/git_repo/hello-node-client/node_modules/launchdarkly-js-sdk-common/src/InspectorManager.js:1:9)**
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/$USER/source/git_repo/hello-node-client/node_modules/launchdarkly-js-sdk-common/src/index.js:17:46)

(node) Warning: Accessing non-existent property 'messages' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:748:11)
    at Object.get (node:internal/modules/cjs/loader:764:5)
    **at Object.<anonymous> (/home/$USER/source/git_repo/hello-node-client/node_modules/launchdarkly-js-sdk-common/src/SafeInspector.js:1:9)**
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/$USER/source/git_repo/hello-node-client/node_modules/launchdarkly-js-sdk-common/src/InspectorManager.js:2:23)

**SDK version**
launchdarky-js-sdk-common: 4.3.2 
launchdarkly-node-client-sdk: 2.2.1

**Language version, developer tools**
node: 16.18.1
npm: 8.19.2

**OS/platform**
Windows 10
Microsoft WSL2

**Additional context**

**Comment by yusinto** [comment]
This has been fixed in [4.3.3](https://github.com/launchdarkly/js-sdk-common/releases/tag/4.3.3) and the node client sdk has been updated accordingly in [2.2.2](https://github.com/launchdarkly/node-client-sdk/releases/tag/2.2.2).
